### ISSUE TITLE
New plot is very expensive for frequent data changes.

### ISSUE THREAD

**Issue by Bob-Thomas** [statnett/vue-plotly#10]
I would advise using Plotly.react instead of newPlot and relayout.
This will simplify your code and instead of rebuilding a whole new plot it just redraws the styling and traces.
[plotly.react docs](https://plot.ly/javascript/plotlyjs-function-reference/#plotlyreact)
I actually wrote a tiny implementation of your bigger idea of embedding vuejs in plotly.js

https://medium.com/@bobthomas295/vuejs-and-plotly-js-reactive-charts-da9b3b59f2dc

Here you can see how easy it is to use the Plotly.react and the speed you get with it.

**Comment by mokkabonna** [comment]
Fixed in 14b8c07

**Comment by Bob-Thomas** [comment]
Sweet

**Comment by manthey** [comment]
Should the window autoresize listener use `react` rather than `newPlot`?

**Comment by mokkabonna** [comment]
Fixed
