### ISSUE TITLE
event doesn't work

### ISSUE THREAD

**Issue by xueenda** [statnett/vue-plotly#16]
v-on:click="plotlyEvent"

This is not working. Please advise!

**Comment by ifigueroap** [comment]
I'm stuck in the same situation... the events are not working

**Comment by Beomi** [comment]
Yes, those events aren't working at all...

**Comment by yejiyang** [comment]
The events are not working. any one any advises?

**Comment by mokkabonna** [comment]
This is working fine for me after the latest update:

```html
    <vue-plotly :data="data" :layout="layout" :options="options" @click="handler"/>
```

```js
methods: {
    handler(event) {
      console.log('handled')
      console.log(event)
    }
}
```

Let me know if you still have problems.
