### ISSUE TITLE
Hiding mode bar for plots?

### ISSUE THREAD

**Issue by mpconte** [statnett/vue-plotly#19]
Is it possible to remove the modebar for a vue plot with this library?

**Comment by cassiebrooks** [comment]
You can pass `:options="{ displayModeBar: false }"` directly to the component.

See [here](https://plot.ly/javascript/configuration-options/#hide-the-modebar) for more details.

**Comment by mpconte** [comment]
I see, I didn't know know that you could pass options like this to plotly. Thanks!

**Comment by soichih** [comment]
I am setting `:options="{ displayModeBar: false }"` but Plotly is still showing the mode bar when I hover over the graph. I might be misunderstanding what displayModeBar does, but does this still work?

**Comment by soichih** [comment]
nvm.. This worked
```
:display-mode-bar="false"
```
