### ISSUE TITLE
How to implement

### ISSUE THREAD

**Issue by ecowed** [statnett/vue-plotly#5]
Hey,

Thanks for putting this together. I am trying to implement this in a Laravel project using Vue and Webpack. I have followed the details in the Readme but when I try to render the component (vue-plotly) it says it's an undefined component - I'm new to VueJS so any help/step-by-step details you'd be able to provide would be fantastic! Cheers! :D

**Comment by mokkabonna** [comment]
Not really that much more to say. Unless you paste code that shows how you currently are using it.

**Comment by HamadaFMahdi** [comment]
@ecowed 
Did you register the component in the components attribute?
