### ISSUE TITLE
autoResize duplicates legend

### ISSUE THREAD

**Issue by soichih** [statnett/vue-plotly#6]
If I set :autoResize="true", it ends up with having multiple listing of the legend everytime resize event fires. 

Before resizing..

![screenshot from 2018-06-05 10-49-25](https://user-images.githubusercontent.com/923896/40983827-71b1b21a-68ae-11e8-982f-8c32628697e7.png)

After resizing..

![screenshot from 2018-06-05 10-48-34](https://user-images.githubusercontent.com/923896/40983596-040de238-68ae-11e8-9a66-fe2ad9fba9a1.png)

Also, autoResize doesn't fire when the plot is first displayed (as resize event hasn't fired yet). So I am calling plot() function when the plot is first displayed. It correctly resizes it, but it has the same side effect of duplicating the legend everytime I call plot().

**Comment by nmearl** [comment]
Seeing the same problem -- any solutions?

**Comment by wbenhallam** [comment]
same issue here...

**Comment by mokkabonna** [comment]
Fixed in 0.2.0

Problem was we called `plot` instead of ``newPlot`

https://plot.ly/javascript/plotlyjs-function-reference/#plotlyplot 

First of all this is deprecated now and it also duplicated the data.

**Comment by soichih** [comment]
It's working!
