### ISSUE TITLE
WebGL context leaking?

### ISSUE THREAD

**Issue by soichih** [statnett/vue-plotly#8]
I am not sure if I need to do something explicit to remove the old view, but vue-plotly seems to be opening but never closing old webgl context once it's no longer used.

After a while, I start seeing the following error message.

```
Error: WebGL warning: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
```

Can it be updated to close the old webgl upon destroy hook?

**Comment by mokkabonna** [comment]
Could be fixed after the change to react instead of newPlot. Closing, open if still an issue.
